# Udacity capstone project dockerfile
FROM tensorflow/tensorflow:1.3.0-gpu
LABEL maintainer="olala7846@gmail.com"

# Add ROS sources and install ros-base
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list' && \
    apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 0xB01FA116 && \
    apt-get update && \
    apt-get install -y ros-kinetic-ros-base \
    python-rosdep \
    python-rosinstall \
    python-rosinstall-generator \
    python-wstool \
    geographiclib-tools \
    ros-kinetic-angles \
    ros-kinetic-geographic-msgs \
    ros-kinetic-geometry \
    && apt-get -y clean all \
    && rm -rf /var/lib/apt/lists/*

# Install Dataspeed DBW https://goo.gl/KFSYi1 from binary
# adding Dataspeed server to apt
RUN sh -c 'echo "deb [ arch=amd64 ] http://packages.dataspeedinc.com/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-dataspeed-public.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FF6D3CDA
RUN apt-get update

# setup rosdep
ENV ROS_DISTRO kinetic
RUN rosdep init
RUN sh -c 'echo "yaml http://packages.dataspeedinc.com/ros/ros-public-'$ROS_DISTRO'.yaml '$ROS_DISTRO'" > /etc/ros/rosdep/sources.list.d/30-dataspeed-public-'$ROS_DISTRO'.list'
RUN rosdep update
RUN apt-get install -y ros-$ROS_DISTRO-dbw-mkz
RUN apt-get upgrade -y
# end installing Dataspeed DBW

# install python packages
RUN pip install Flask==0.11.1 attrdict==2.0.0 eventlet==0.19.0 python-socketio==1.6.1 numpy==1.13.1 Pillow==6.0.0 scipy==0.19.1


# install required ros dependencies
RUN apt-get install -y ros-$ROS_DISTRO-cv-bridge
RUN apt-get install -y ros-$ROS_DISTRO-pcl-ros
RUN apt-get install -y ros-$ROS_DISTRO-image-proc

# socket io
RUN apt-get install -y netbase

# tfinterface
RUN pip install git+https://github.com/kiwicampus/tfinterface.git@develop


RUN mkdir /capstone
VOLUME ["/capstone"]
VOLUME ["/root/.ros/log/"]
WORKDIR /capstone/ros
